name: ndef_record
description: A Dart package implementing the NFC Data Exchange Format (NDEF).
version: 1.4.0
repository: https://github.com/okadan/dart-ndef-record

environment:
  sdk: ^3.10.0

dependencies:
  collection: ^1.19.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.27.0
